app:
  build: .
  volumes:
    - .:/app
  env_file:
    - .env
  links:
    - db
  ports:
    - "3000:3000"
  command: web
  environment:
    VIRTUAL_HOST: crier.docker
worker:
  image: crierprxorg_app
  volumes:
    - .:/app
  env_file:
    - .env
  links:
    - db
  command: worker
db:
  image: postgres
  env_file:
    - .env
  ports:
    - "5432:5432"
